import React from 'react';
import { FullLessonPackage } from '../types';

interface PrintableLessonPackProps {
  lessonPackage: FullLessonPackage;
}

export const PrintableLessonPack: React.FC<PrintableLessonPackProps> = ({ lessonPackage }) => {
  return (
    <div className="hidden print:block p-8 bg-white text-black font-sans max-w-4xl mx-auto space-y-6">
      {/* Printable Header */}
      <div className="border-b-2 border-black pb-4 text-center">
        <h1 className="text-2xl font-bold uppercase tracking-tight">TEACHMATE AI — Official Lesson Package</h1>
        <p className="text-sm font-semibold">NERDC Primary School Curriculum Standard</p>
        <div className="flex justify-center gap-6 text-xs mt-2 font-bold">
          <span>Subject: {lessonPackage.subject}</span>
          <span>Grade: {lessonPackage.grade}</span>
          <span>Duration: {lessonPackage.durationMinutes} Mins</span>
        </div>
      </div>

      {/* Lesson Details */}
      <div>
        <h2 className="text-xl font-bold border-b border-gray-400 pb-1 mb-2">Topic: {lessonPackage.topic}</h2>
        <p className="text-xs italic">NERDC Benchmark Code: {lessonPackage.citationVerification?.nerdcBenchmarkCode}</p>
      </div>

      {/* Lesson Plan */}
      <div className="space-y-2">
        <h3 className="text-lg font-bold bg-gray-100 p-2 border">1. Behavioral Objectives</h3>
        <ul className="list-disc list-inside text-sm space-y-1">
          {lessonPackage.lessonPlan.behavioralObjectives.map((obj, i) => (
            <li key={i}>{obj}</li>
          ))}
        </ul>
      </div>

      <div className="space-y-2">
        <h3 className="text-lg font-bold bg-gray-100 p-2 border">2. Materials Needed</h3>
        <p className="text-sm">{lessonPackage.lessonPlan.materialsNeeded.join(', ')}</p>
      </div>

      {/* Delivery Steps Table */}
      <div className="space-y-2">
        <h3 className="text-lg font-bold bg-gray-100 p-2 border">3. 5-Step Delivery Plan</h3>
        <table className="w-full text-left text-xs border-collapse border border-gray-300">
          <thead>
            <tr className="bg-gray-200 border-b border-gray-300">
              <th className="p-2 border border-gray-300">Step</th>
              <th className="p-2 border border-gray-300">Duration</th>
              <th className="p-2 border border-gray-300">Teacher Activity</th>
              <th className="p-2 border border-gray-300">Pupil Activity</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(lessonPackage.lessonPlan.deliverySteps).map(([key, valRaw]) => {
              const val = valRaw as { duration: string; teacherActivity: string; pupilActivity: string };
              return (
                <tr key={key} className="border-b border-gray-300">
                  <td className="p-2 font-bold uppercase border border-gray-300">{key}</td>
                  <td className="p-2 border border-gray-300">{val.duration}</td>
                  <td className="p-2 border border-gray-300">{val.teacherActivity}</td>
                  <td className="p-2 border border-gray-300">{val.pupilActivity}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Learner Notes */}
      <div className="space-y-2">
        <h3 className="text-lg font-bold bg-gray-100 p-2 border">4. Student Notes</h3>
        <p className="text-sm leading-relaxed">{lessonPackage.learnerNotes.summaryText}</p>
        <h4 className="font-bold text-sm mt-2">Key Vocabulary:</h4>
        <ul className="list-disc list-inside text-xs space-y-1">
          {lessonPackage.learnerNotes.keyVocabulary.map((v, i) => (
            <li key={i}>
              <span className="font-bold">{v.term}:</span> {v.definition}
            </li>
          ))}
        </ul>
      </div>

      {/* Quiz */}
      <div className="space-y-2 page-break-before">
        <h3 className="text-lg font-bold bg-gray-100 p-2 border">5. Pupil Assessment Quiz</h3>
        {lessonPackage.quiz.questions.map((q) => (
          <div key={q.id} className="text-xs space-y-1 border-b border-gray-200 pb-2">
            <p className="font-bold">{q.id}. {q.questionText}</p>
            {q.options && <p className="text-gray-700">{q.options.join('   ')}</p>}
            <p className="font-semibold text-gray-900">Answer: {q.correctAnswer}</p>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="border-t border-gray-400 pt-4 text-center text-xs text-gray-500">
        Generated by TeachMate AI — Primary School Teacher Assistant • Approved for Classroom Distribution
      </div>
    </div>
  );
};
